import { test } from "node:test";
import assert from "node:assert/strict";
import { findPendingToolUse, describeTool, parseSpoolLine, extractForwardable } from "../src/transcript.ts";

const asst = (id: string, name: string, input: Record<string, unknown>) =>
  JSON.stringify({
    type: "assistant",
    isSidechain: false,
    message: { content: [{ type: "tool_use", id, name, input }] },
  });

const result = (toolUseId: string) =>
  JSON.stringify({
    type: "user",
    isSidechain: false,
    message: { content: [{ type: "tool_result", tool_use_id: toolUseId, content: "ok" }] },
  });

test("findPendingToolUse returns the unmatched tool_use", () => {
  const jsonl = [
    asst("toolu_1", "Bash", { command: "pnpm test" }),
    result("toolu_1"),
    asst("toolu_2", "Edit", { file_path: "src/x.ts" }),
  ].join("\n");
  assert.deepEqual(findPendingToolUse(jsonl), { name: "Edit", input: { file_path: "src/x.ts" } });
});

test("findPendingToolUse returns null when all tools have results", () => {
  const jsonl = [asst("toolu_1", "Bash", { command: "ls" }), result("toolu_1")].join("\n");
  assert.equal(findPendingToolUse(jsonl), null);
});

test("findPendingToolUse ignores subagent (sidechain) tool_use", () => {
  const side = JSON.stringify({
    type: "assistant",
    isSidechain: true,
    message: { content: [{ type: "tool_use", id: "toolu_side", name: "Grep", input: { pattern: "x" } }] },
  });
  const jsonl = [asst("toolu_1", "Bash", { command: "ls" }), result("toolu_1"), side].join("\n");
  assert.equal(findPendingToolUse(jsonl), null);
});

test("findPendingToolUse tolerates a torn final line and blank lines", () => {
  const jsonl = [asst("toolu_1", "Write", { file_path: "a.ts" }), "", '{"type":"assist'].join("\n");
  assert.deepEqual(findPendingToolUse(jsonl), { name: "Write", input: { file_path: "a.ts" } });
});

test("describeTool summarizes by the most relevant arg", () => {
  assert.equal(describeTool({ name: "Bash", input: { command: "pnpm test" } }), "Bash: pnpm test");
  assert.equal(describeTool({ name: "Edit", input: { file_path: "src/x.ts" } }), "Edit: src/x.ts");
  assert.equal(describeTool({ name: "WebFetch", input: { url: "https://x.dev" } }), "WebFetch: https://x.dev");
  assert.equal(describeTool({ name: "Task", input: {} }), "Task");
});

test("describeTool clips long commands and collapses whitespace", () => {
  const out = describeTool({ name: "Bash", input: { command: "echo " + "a".repeat(300) } });
  assert.ok(out.length <= "Bash: ".length + 200);
  assert.ok(out.endsWith("…"));
});

const userText = (text: string, extra: Record<string, unknown> = {}) =>
  JSON.stringify({ type: "user", message: { role: "user", content: text }, ...extra });

const asstText = (text: string, extra: Record<string, unknown> = {}) =>
  JSON.stringify({ type: "assistant", message: { role: "assistant", content: [{ type: "text", text }] }, ...extra });

test("extractForwardable keeps user + assistant text in order", () => {
  const jsonl = [
    userText("how are things?", { uuid: "u1" }),
    asstText("all good, you?", { uuid: "a1" }),
  ].join("\n");
  assert.deepEqual(extractForwardable(jsonl), [
    { role: "user", text: "how are things?", uuid: "u1", ts: undefined },
    { role: "assistant", text: "all good, you?", uuid: "a1", ts: undefined },
  ]);
});

test("extractForwardable drops thinking, tool_use, and tool_result", () => {
  const jsonl = [
    JSON.stringify({ type: "assistant", message: { content: [{ type: "thinking", thinking: "hmm" }] } }),
    JSON.stringify({ type: "assistant", message: { content: [{ type: "tool_use", id: "t1", name: "Bash", input: {} }] } }),
    JSON.stringify({ type: "user", message: { content: [{ type: "tool_result", tool_use_id: "t1", content: "ok" }] } }),
    asstText("done — 3 pods up"),
  ].join("\n");
  assert.deepEqual(extractForwardable(jsonl).map((m) => m.text), ["done — 3 pods up"]);
});

test("extractForwardable skips isMeta, isSidechain, and metadata lines", () => {
  const jsonl = [
    JSON.stringify({ type: "last-prompt", content: "undefined" }),
    userText("/some-command body", { isMeta: true }),
    asstText("sidechain reply", { isSidechain: true }),
    asstText("real reply"),
  ].join("\n");
  assert.deepEqual(extractForwardable(jsonl).map((m) => m.text), ["real reply"]);
});

test("extractForwardable filters command/bash/caveat wrappers", () => {
  const jsonl = [
    userText("<command-name>/pods</command-name>"),
    userText("<local-command-stdout>output</local-command-stdout>"),
    userText("Caveat: The messages below were generated by the user"),
    userText("[Request interrupted by user for tool use]"),
    userText("a genuine question"),
  ].join("\n");
  assert.deepEqual(extractForwardable(jsonl).map((m) => m.text), ["a genuine question"]);
});

test("extractForwardable resumes strictly after sinceUuid", () => {
  const jsonl = [
    asstText("first", { uuid: "a1" }),
    asstText("second", { uuid: "a2" }),
    asstText("third", { uuid: "a3" }),
  ].join("\n");
  assert.deepEqual(extractForwardable(jsonl, "a2").map((m) => m.text), ["third"]);
  assert.deepEqual(extractForwardable(jsonl, "nope").map((m) => m.text), ["first", "second", "third"]);
});

test("extractForwardable tolerates torn final line and blank lines", () => {
  const jsonl = [asstText("kept"), "", '{"type":"assist'].join("\n");
  assert.deepEqual(extractForwardable(jsonl).map((m) => m.text), ["kept"]);
});

test("parseSpoolLine accepts a valid event and rejects junk", () => {
  const line = JSON.stringify({ ts: 1, kind: "permission", pod: "p1", session: "s1" });
  assert.deepEqual(parseSpoolLine(line), { ts: 1, kind: "permission", pod: "p1", session: "s1" });
  assert.equal(parseSpoolLine("{not json"), null);
  assert.equal(parseSpoolLine(JSON.stringify({ kind: "idle" })), null);
});
